version: "2.2"
services:
  # https://www.elastic.co/guide/en/apm/server/current/running-on-docker.html
  apm-server:
    #image: docker.elastic.co/apm/apm-server:6.2.3
    build:
        context: .
    container_name: apm-server
    ports:
      - 8200:8200
    networks:
      - apm-net
    volumes:
      - "./apm-server.yml:/usr/share/apm-server/apm-server.yml"
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: --strict.perms=false -e  # Avoid the error: "apm-server.yml" can only be writable by the owner.

  # https://www.elastic.co/guide/en/kibana/current/_configuring_kibana_on_docker.html
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: apm-kibana
    ports:
      - 5601:5601
    networks:
      - apm-net
    volumes:
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"
    depends_on:
      elasticsearch:
        condition: service_healthy

  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: apm-es
    environment:
      - "ELASTIC_PASSWORD=changeme"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ports:
      - 9200:9200
    networks:
      - apm-net
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    healthcheck:
      test: ['CMD', 'curl', '-f', '-u', 'elastic:changeme', 'http://localhost:9200']
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  
      #    # Logstash
      #  logstash:
      #    image: docker.elastic.co/logstash/logstash:7.0.0
      #    container_name: logstash
      #    environment: 
      #      - XPACK.MONITORING_ELASTICSEARCH_HOSTS="http://elasticsearch:9200" 
      #    ports:
      #      - 5000:5000
      #      - 5044:5044
      #      - 5000:5000/udp
      #      - 9600:9600
      #      - 9700:9700
      #    networks:
      #      - apm-net
      #    volumes:
      #      - "$PWD/pipeline:/usr/share/logstash/pipeline/"
      #    depends_on:
      #      elasticsearch:
      #        condition: service_healthy


volumes:
  esdata:
    driver: local

networks:
  apm-net:
